"""Generate the decomposed responder policy table from the replay population."""

from __future__ import annotations

import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from policy.costs import ACTION_TIERS, c_rto, tier_costs
from policy.elkan import apply_policy
from responder.replay import _data
from responder.trust import Tagged, Tier

OUT_PATH = ROOT / "eval" / "responder" / "policy_table.md"
BOOTSTRAPS = 2_000
SEED = 20260901


def _hand_rule(features):
    text = (ROOT / "eval" / "policy.md").read_text(encoding="utf-8")
    match = re.search(r"order_value > ([\d,]+\.\d+) BRL AND customer", text)
    if match is None:
        raise ValueError("existing hand-rule threshold not found in eval/policy.md")
    threshold = float(match.group(1).replace(",", ""))
    value = np.nan_to_num(features["order_value"].to_numpy(dtype=float), nan=0.0)
    new_customer = np.nan_to_num(features["cust_prior_orders"].to_numpy(dtype=float), nan=0.0) == 0
    return np.where((value > threshold) & new_customer, "prepaid_only", "allow")


def _choices(features, labels, reasons, probabilities):
    policy = apply_policy(probabilities, features, reasons)
    return {
        "Intervene on nothing": np.full(len(labels), "allow"),
        "Intervene on everything": np.full(len(labels), "prepaid_only"),
        "Hand-written business rule": _hand_rule(features),
        "Model + cost policy": policy.tier,
    }


def _metrics(features, labels, choices):
    costs = tier_costs(features)
    value = np.nan_to_num(features["order_value"].to_numpy(dtype=float), nan=0.0)
    freight = np.nan_to_num(features["order_freight"].to_numpy(dtype=float), nan=0.0)
    rto = c_rto(value, freight)
    treated = choices != "allow"
    failures = labels.astype(bool) & treated
    impression = np.zeros(len(labels))
    triggered = np.zeros(len(labels))
    for tier in ACTION_TIERS:
        selected = choices == tier
        impression[selected] = costs[tier]["impression"][selected]
        triggered[selected] = costs[tier]["triggered"][selected] * (~labels[selected].astype(bool))
    return {
        "treated": Tagged(int(treated.sum()), Tier.MEASURED, "observed_treated_set"),
        "failures": Tagged(int(failures.sum()), Tier.MEASURED, "observed_treated_failures"),
        "impression": Tagged(float(impression.sum()), Tier.MEASURED, "observed_impression_cost"),
        "triggered": Tagged(float(triggered.sum()), Tier.MEASURED, "observed_triggered_cost"),
        "break_even": Tagged(
            float((impression.sum() + triggered.sum()) / max(rto[failures].sum(), 1e-12)),
            Tier.MEASURED,
            "observed_costs_divided_by_observed_treated_failure_rto",
        ),
        "_numerator": impression + triggered,
        "_denominator": np.where(labels.astype(bool) & treated, rto, 0.0),
    }


def generate() -> str:
    _, features, labels, reasons, probabilities = _data()
    choices = _choices(features, labels, reasons, probabilities)
    rng = np.random.default_rng(SEED)
    indices = rng.integers(0, len(labels), size=(BOOTSTRAPS, len(labels)))
    rows = []
    for name, selected in choices.items():
        metrics = _metrics(features, labels, selected)
        numerator = metrics["_numerator"]
        denominator = metrics["_denominator"]
        sampled = numerator[indices].sum(axis=1) / np.maximum(
            denominator[indices].sum(axis=1), 1e-12
        )
        if denominator.sum() == 0:
            sampled[:] = 0.0
        ci_low, ci_high = np.percentile(sampled, (2.5, 97.5))
        rows.append(
            f"| {name} | {metrics['treated'].value:,} [{metrics['treated'].tier.name}] | "
            f"{metrics['failures'].value:,} [{metrics['failures'].tier.name}] | "
            f"{metrics['impression'].value:,.2f} [{metrics['impression'].tier.name}] | "
            f"{metrics['triggered'].value:,.2f} [{metrics['triggered'].tier.name}] | "
            f"{metrics['break_even'].value:.2%} [{metrics['break_even'].tier.name}] | "
            f"[{ci_low:.2%}, {ci_high:.2%}] [MEASURED] |"
        )
    return "\n".join([
        "# Responder policy table - decomposed measured quantities",
        "",
        "Generated by `responder/policy_table.py` from the primary risk-set test window. "
        "The existing hand-rule threshold is consumed from `eval/policy.md`; it is not "
        "re-derived here.",
        "",
        "> **Caption.** There is deliberately no **RTO cost avoided** or **Net** column. "
        "Both require an effectiveness prior and would turn this measured table into an "
        "assumed claim. The absent column is the argument. CIs are 2,000 paired bootstrap "
        "resamples over identical test rows.",
        "",
        "| Policy | Orders treated | Failures in treated set | Impression cost | "
        "Expected triggered cost | Break-even E | CI |",
        "|---|---:|---:|---:|---:|---:|---|",
        *rows,
        "",
    ])


def main() -> int:
    OUT_PATH.write_text(generate(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())