#!/usr/bin/env python3
"""
Primary and secondary target declaration, and the sample-size trade-off between them.

PRIMARY    label_b on the risk set  ->  P(fails | ships)
SECONDARY  label_a on all matured   ->  P(fails)

The secondary target is not a fallback.  It is carried so the cost of conditioning is
reported rather than assumed: label_a buys 2.5x the test positives and a correspondingly
tighter minimum detectable difference, at the cost of a target that mixes stock and
seller-side fulfilment failures in with delivery failures.

Writes eval/label_targets.md.  Deterministic; no model, no sampling.
"""

from __future__ import annotations

import math
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from data.loader import (  # noqa: E402
    CUSTOMERS_CSV,
    ORDERS_CSV,
    PRIMARY_LABEL,
    SECONDARY_LABEL,
    OlistLoader,
)

OUT_PATH = REPO_ROOT / "eval" / "label_targets.md"

Z_ALPHA_TWO_SIDED_05 = 1.959963984540054
Z_POWER_80 = 0.8416212335729143


def min_detectable_diff(ap: float, n_pos: int, rho: float = 0.8) -> float:
    """Held identical to eval/positive_counts.md section 6."""
    se = math.sqrt(ap * (1.0 - ap) / n_pos)
    return (Z_ALPHA_TWO_SIDED_05 + Z_POWER_80) * se * math.sqrt(2.0 * (1.0 - rho))


def main() -> int:
    loader = OlistLoader()
    labelled = loader.labelled()
    risk = loader.risk_set()

    is_test = labelled["is_test"]
    risk_test = risk["is_test"]

    # Primary: label_b evaluated on the risk set.
    p_train_rows = int((~risk_test).sum())
    p_test_rows = int(risk_test.sum())
    p_train_pos = int((risk["label_b"] & ~risk_test).sum())
    p_test_pos = int((risk["label_b"] & risk_test).sum())

    # Secondary: label_a evaluated on the full matured population.
    s_train_rows = int((~is_test).sum())
    s_test_rows = int(is_test.sum())
    s_train_pos = int((labelled["label_a"] & ~is_test).sum())
    s_test_pos = int((labelled["label_a"] & is_test).sum())

    excluded = labelled[~labelled["entered_fulfillment"]]
    excluded_test = int((~labelled["entered_fulfillment"] & is_test).sum())

    def pct(a, b) -> str:
        return f"{100.0 * a / b:.3f}%" if b else "-"

    L: list[str] = []
    w = L.append

    w("# Target definition: primary and secondary")
    w("")
    w("Generated by `scripts/02_label_targets.py`. Companions: "
      "`eval/positive_counts.md`, `eval/label_composition.md`.")
    w("Deterministic; no model, no sampling.")
    w("")
    w(f"- Generated (UTC): `{datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S}`")
    for name, digest in loader.checksums(ORDERS_CSV, CUSTOMERS_CSV).items():
        w(f"- `{name}` sha256: `{digest}`")
    w("")

    w("## 1. What the model predicts")
    w("")
    w("The estimand is **P(fails | ships)** - the probability an order fails to reach "
      "`delivered`, *given that it was handed to a carrier*. It is not P(fails).")
    w("")
    w("The risk set is `order_delivered_carrier_date IS NOT NULL`. Orders that never "
      "shipped are removed from the population, not scored as negatives.")
    w("")
    w("Return-to-origin is a post-shipment event by definition. An order cancelled in "
      "the warehouse, or whose stock turns out `unavailable`, cannot return to origin - "
      "it never survived to the point where the risk exists. Scoring those orders as "
      "negatives would put rows in the denominator that were never at risk, understating "
      "prevalence and rewarding the model for assigning low risk to outcomes it neither "
      "observes nor can act on.")
    w("")
    w(f"On this panel the restriction removes **{len(excluded):,} of {len(labelled):,} "
      f"matured orders** ({pct(len(excluded), len(labelled))}), of which "
      f"**{excluded_test:,}** fall in the test window.")
    w("")
    w("Statuses removed:")
    w("")
    w("| `order_status` | Orders removed |")
    w("|---|---:|")
    for status, n in excluded["order_status"].value_counts().items():
        w(f"| `{status}` | {n:,} |")
    w(f"| **Total** | **{len(excluded):,}** |")
    w("")
    n_delivered_no_carrier = int((excluded["order_status"] == "delivered").sum())
    if n_delivered_no_carrier:
        w(f"The {n_delivered_no_carrier} `delivered` rows are a data quirk, not a "
          "modelling choice: they reached the customer but carry no carrier date. They "
          "would have been negatives on either target, so removing them shifts no "
          "positive count; they are listed rather than silently dropped.")
        w("")
    w("### What conditioning costs")
    w("")
    w("`order_delivered_carrier_date` is a **post-checkout** field. Conditioning the "
      "population on it means selecting on something not knowable at scoring time, so:")
    w("")
    w("- The deployed score is valid *conditional on shipment*. Unconditional risk is "
      "P(ships) x P(fails | ships); a consumer needing the unconditional quantity must "
      "multiply by a shipment probability this repo does not model.")
    w("- Selection into the risk set is not random - orders leave for reasons "
      "(seller-side cancellation, stock unavailability) that plausibly correlate with "
      "the covariates. This is conditioning on a post-treatment variable. It does not "
      "invalidate the predictive claim on the subpopulation, which is what the score is "
      "used for, but it does bar a causal reading of the coefficients.")
    w("")
    w("The column is used for this and nothing else. It is excluded from every feature "
      "matrix, enforced behaviourally in `tests/test_leakage.py`; see "
      "`data/COLUMN_WHITELIST.md`.")
    w("")

    w("## 2. The two targets")
    w("")
    w("| | PRIMARY | SECONDARY |")
    w("|---|---|---|")
    w(f"| Label | `{PRIMARY_LABEL}` | `{SECONDARY_LABEL}` |")
    w("| Definition | entered fulfillment and never delivered | any non-delivered |")
    w("| Population | risk set (shipped) | all matured orders |")
    w("| Estimand | **P(fails \\| ships)** | P(fails) |")
    w(f"| Train rows | {p_train_rows:,} | {s_train_rows:,} |")
    w(f"| Test rows | {p_test_rows:,} | {s_test_rows:,} |")
    w(f"| Train positives | {p_train_pos:,} | {s_train_pos:,} |")
    w(f"| **Test positives** | **{p_test_pos:,}** | **{s_test_pos:,}** |")
    w(f"| Train prevalence | {pct(p_train_pos, p_train_rows)} | "
      f"{pct(s_train_pos, s_train_rows)} |")
    w(f"| Test prevalence | {pct(p_test_pos, p_test_rows)} | "
      f"{pct(s_test_pos, s_test_rows)} |")
    w("")
    w("Every reported probability, calibration curve, and policy threshold is on the "
      "**primary** scale unless explicitly labelled otherwise. The secondary target is "
      "computed alongside on every run and reported as a benchmark - never substituted "
      "for the primary when the primary is inconvenient.")
    w("")

    w("## 3. The sample-size trade-off")
    w("")
    w("Minimum detectable PR-AUC difference at each target's test positive count, on "
      "the approximation stated in `eval/positive_counts.md` section 6 "
      "(alpha = 0.05 two-sided, power = 0.80, paired at rho = 0.8).")
    w("")
    w(f"| Assumed AP | PRIMARY (n_pos = {p_test_pos}) | "
      f"SECONDARY (n_pos = {s_test_pos}) | Ratio |")
    w("|---:|---:|---:|---:|")
    for ap in (0.05, 0.10, 0.20, 0.30):
        a = min_detectable_diff(ap, p_test_pos)
        b = min_detectable_diff(ap, s_test_pos)
        w(f"| {ap:.2f} | {a:.3f} | {b:.3f} | {a / b:.2f}x |")
    w("")
    ratio = min_detectable_diff(0.10, p_test_pos) / min_detectable_diff(0.10, s_test_pos)
    w(f"**This is the cost of the primary target, stated as a number.** A model "
      f"comparison on the primary label needs a gap **{ratio:.2f}x larger** to resolve "
      f"than the same comparison on the secondary. At AP = 0.10 that is "
      f"{min_detectable_diff(0.10, p_test_pos):.3f} against "
      f"{min_detectable_diff(0.10, s_test_pos):.3f} AP.")
    w("")
    w("Both clear the 150-positive threshold from `eval/positive_counts.md` section 5, "
      f"but the primary clears it by {p_test_pos - 150} positives. Ablations that were "
      "already marginal at 379 positives are not resolvable at "
      f"{p_test_pos} - any comparison below the primary threshold is reported as "
      '"not resolvable at this sample size", on the primary label, not quietly rerun on '
      "the secondary until it resolves.")
    w("")

    w("## 4. Why the primary is the smaller target")
    w("")
    w("The secondary has 2.5x the positives and would produce tighter intervals on "
      "every comparison. It is not the headline because a larger sample of the wrong "
      "quantity is not worth more than a smaller sample of the right one.")
    w("")
    n_never = int((labelled["label_a"] & ~labelled["entered_fulfillment"]).sum())
    w(f"Of the secondary target's {s_train_pos + s_test_pos:,} positives, "
      f"**{n_never:,} never reached a carrier** - stock unavailability and seller-side "
      "cancellation, a different causal generator from a delivery failure and one no "
      "checkout-time intervention addresses. A confirmation SMS does not fix a stockout. "
      "Ranking those correctly earns PR-AUC that the policy layer cannot convert into "
      "avoided cost.")
    w("")
    w("The primary target is narrower, closer to doorstep refusal, and its positives are "
      "the ones an intervention could plausibly have changed. Reporting both is what "
      "keeps that choice honest: the trade-off is on the page in section 3, quantified, "
      "rather than asserted.")
    w("")

    w("## 5. This supersedes a conclusion in `eval/positive_counts.md`")
    w("")
    mdd_379 = min_detectable_diff(0.10, s_test_pos)
    mdd_primary = min_detectable_diff(0.10, p_test_pos)
    w("Section 7 of `eval/positive_counts.md` recommends reinstating the EBM ablation "
      "(ARCHITECTURE.md sections 5.4, 15) on the grounds that the gate returned a larger "
      f"test set than estimated. That was computed against {s_test_pos} all-orders test "
      f"positives, giving a resolvable gap of ~{mdd_379:.3f} AP.")
    w("")
    w(f"**On the primary target that recommendation no longer holds as written.** At "
      f"{p_test_pos} test positives the resolvable gap is ~{mdd_primary:.3f} AP. Section "
      "5.4 describes the interesting EBM case as a difference of roughly 1 AP point; "
      f"that was already out of reach at {s_test_pos} positives and is further out of "
      f"reach at {p_test_pos}. The ablation is still worth running on the secondary "
      "target as a benchmark, but a null result there must be reported as unresolved "
      "rather than as evidence the two models are equivalent, and it cannot be "
      "transferred to the primary target.")
    w("")
    w("The step 0 artifact is left as written rather than edited after the fact - it "
      "records what was true given the gate's own decision rule. This section is the "
      "correction.")
    w("")

    report = "\n".join(L) + "\n"
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(report, encoding="utf-8")
    print(report)
    print(f"[written] {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
