#!/usr/bin/env python3
"""
Step 1 output: build the point-in-time feature matrix and report on it.

Writes:
    eval/feature_report.md      per-column null rates, PIT compliance, split sizes,
                                calibration window candidates
    artifacts/features.parquet  the matrix itself, if pyarrow is available

No model is trained.  Nothing here fits anything.

Deterministic: no sampling, no randomness.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from data.loader import (  # noqa: E402
    CUSTOMERS_CSV,
    ITEMS_CSV,
    ORDERS_CSV,
    PAYMENTS_CSV,
    PRIMARY_LABEL,
    VALIDATION_DAYS,
    OlistLoader,
)
from features.builder import (  # noqa: E402
    CUSTOMER_SMOOTHING,
    DEFAULT_GROUPS,
    HISTORY_TARGET,
    PINCODE_SMOOTHING,
    FeatureBuilder,
)
from features.calibration import (  # noqa: E402
    MIN_EVENTS_PER_PARAM,
    PLATT_N_PARAMS,
    calibration_window_candidates,
)
from features.pit import PITViolation, assert_truncation_invariant  # noqa: E402

OUT_PATH = REPO_ROOT / "eval" / "feature_report.md"
MATRIX_PATH = REPO_ROOT / "artifacts" / "features.parquet"

TS = "order_purchase_timestamp"

GROUP_OF = {
    "order": (
        "order_value", "order_freight", "freight_ratio", "log_order_value", "n_items",
        "n_sellers", "n_products", "avg_item_price", "payment_value",
        "payment_installments", "n_payment_types", "is_boleto", "product_weight_g",
        "product_volume_cm3", "product_photos_qty", "product_category", "purchase_hour",
        "purchase_dow", "purchase_month", "purchase_is_weekend",
    ),
    "customer": (
        "cust_prior_orders", "cust_prior_failures", "cust_prior_failure_rate",
        "cust_prior_avg_value", "cust_days_since_prior_order", "cust_prior_boleto_ratio",
    ),
    "pincode": (
        "pincode_prior_orders", "pincode_prior_failures",
        "pincode_failure_rate_smoothed", "global_prior_failure_rate",
    ),
    "availability": (
        "has_item_rows", "has_payment_row", "has_product_metadata", "has_zip_prefix",
        "n_missing_features",
    ),
}


def main() -> int:
    loader = OlistLoader()
    population = loader.risk_set()
    splits = loader.split_labelled()
    population = population.join(splits["split"], how="left")

    builder = FeatureBuilder()
    matrix = builder.build(population)

    # PIT verification, run for real rather than asserted in prose.
    cut = population[TS].quantile(0.6)
    try:
        assert_truncation_invariant(builder, population, cut)
        pit_full = "PASS"
        pit_detail = ""
    except PITViolation as exc:  # pragma: no cover - a failure here stops the build
        pit_full = "FAIL"
        pit_detail = str(exc)

    group_results = {}
    for group in DEFAULT_GROUPS:
        try:
            assert_truncation_invariant(
                FeatureBuilder(groups=(group,)), population, cut
            )
            group_results[group] = "PASS"
        except PITViolation as exc:  # pragma: no cover
            group_results[group] = f"FAIL — {exc}"

    candidates = calibration_window_candidates(loader)

    def pct(a, b) -> str:
        return f"{100.0 * a / b:.2f}%" if b else "-"

    L: list[str] = []
    w = L.append

    w("# Feature matrix report")
    w("")
    w("Step 1 output. Generated by `scripts/03_feature_matrix.py`. "
      "**No model is trained.**")
    w("Deterministic: no sampling, no randomness.")
    w("")
    w(f"- Generated (UTC): `{datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S}`")
    for name, digest in loader.checksums(
        ORDERS_CSV, CUSTOMERS_CSV, ITEMS_CSV, PAYMENTS_CSV
    ).items():
        w(f"- `{name}` sha256: `{digest}`")
    w("")
    w(f"Matrix: **{len(matrix):,} rows x {len(matrix.columns)} columns**, built on the "
      f"risk set (the population the primary target `{PRIMARY_LABEL}` is defined on).")
    w("")

    # -- PIT ---------------------------------------------------------------------------
    w("## 1. Point-in-time compliance")
    w("")
    w("Verified by truncation invariance, not by inspection: the matrix is built on the "
      "full panel, built again on the panel truncated to `ts < cut`, and the surviving "
      "rows are required to be identical. A feature that read data at or after its own "
      "timestamp changes when that data is removed.")
    w("")
    w(f"Cut used: `{cut}` (60th percentile of purchase timestamp).")
    w("")
    w("| Scope | Result |")
    w("|---|---|")
    w(f"| Full matrix | **{pit_full}** |")
    for group, result in group_results.items():
        w(f"| Group `{group}` | **{result}** |")
    if pit_detail:
        w("")
        w(f"```\n{pit_detail}\n```")
    w("")
    w("Ties are handled explicitly: two orders sharing a timestamp do not see each "
      "other. A naive `cumsum().shift(1)` gets this wrong — it lets the second row in a "
      "tie block read the first, which is a same-instant read rather than a prior one. "
      "`tests/test_golden_fixtures.py` pins the tie case.")
    w("")
    w("**History encodings aggregate `label_a`, not the primary target.** `label_b` is "
      "defined by `order_delivered_carrier_date`, and encoding it would make a feature "
      "depend on that column transitively. Using `label_a` keeps the invariant absolute: "
      "no feature reads the carrier date, directly or transitively. The cost is that the "
      "encoding targets a broader outcome than the model predicts; as a predictor that "
      "is a larger and better-populated signal, and it carries no coupling to the "
      "target's defining column.")
    w("")

    # -- splits ------------------------------------------------------------------------
    w("## 2. Three-way chronological split")
    w("")
    w(f"Validation is the last **{VALIDATION_DAYS} days** before the test boundary, set "
      "to the longest calibration-window candidate so every candidate nests inside it "
      "and none can reach past the boundary into test.")
    w("")
    w("| Split | Orders | Positives | Prevalence | From | To |")
    w("|---|---:|---:|---:|---|---|")
    for name in ("train", "validation", "test"):
        sub = population[population["split"] == name]
        n_pos = int(sub[PRIMARY_LABEL].sum())
        w(f"| {name} | {len(sub):,} | {n_pos:,} | {pct(n_pos, len(sub))} | "
          f"{sub[TS].min():%Y-%m-%d} | {sub[TS].max():%Y-%m-%d} |")
    w("")
    w("Validation and test are disjoint by construction and asserted in "
      "`tests/test_three_way_split.py`. Validation carries both the early-stopping "
      "signal and the Platt fit, which is what ARCHITECTURE.md §6 specifies; it does "
      "mean the calibration map is fit on data the model early-stopped against, and "
      "that is stated rather than hidden.")
    w("")

    # -- calibration -------------------------------------------------------------------
    floor = MIN_EVENTS_PER_PARAM * PLATT_N_PARAMS
    w("## 3. Calibration window candidates")
    w("")
    w(f"Trailing windows before the test boundary, on the primary target. Platt fits "
      f"{PLATT_N_PARAMS} parameters, so the admissibility floor is "
      f"{MIN_EVENTS_PER_PARAM} events per parameter = **{floor} positives**. A candidate "
      "below it is dropped with a stated reason rather than fitted badly.")
    w("")
    w("| Window | Orders | Positives | Prevalence | Events/param | Admissible |")
    w("|---:|---:|---:|---:|---:|---|")
    for c in candidates:
        mark = "yes" if c.admissible else "**no**"
        w(f"| {c.days}d | {c.n_orders:,} | {c.n_positives:,} | "
          f"{100 * c.prevalence:.3f}% | {c.events_per_param:.1f} | {mark} |")
    w("")
    excluded = [c for c in candidates if not c.admissible]
    if excluded:
        w("**Exclusions:**")
        w("")
        for c in excluded:
            w(f"- **{c.days}d — dropped.** {c.exclusion_reason}")
        w("")
    else:
        w(f"**No candidate is excluded on positive count.** The thinnest window "
          f"({candidates[0].days}d) carries {candidates[0].n_positives} positives, "
          f"{candidates[0].events_per_param:.1f} per parameter, comfortably above the "
          f"{MIN_EVENTS_PER_PARAM} floor. Sample size is not the binding constraint here.")
        w("")

    test_prev = candidates[0].test_prevalence
    w("### The constraint that does bind: prevalence drift")
    w("")
    w(f"The test window the calibration map will be applied to has a prevalence of "
      f"**{100 * test_prev:.3f}%**. The candidates do not match it, and they do not "
      "match each other:")
    w("")
    w("| Window | Prevalence | Ratio vs test |")
    w("|---:|---:|---:|")
    for c in candidates:
        w(f"| {c.days}d | {100 * c.prevalence:.3f}% | {c.prevalence_ratio:.2f}x |")
    w("")
    worst = max(candidates, key=lambda c: c.prevalence_ratio)
    best = min(candidates, key=lambda c: c.prevalence_ratio)
    w(f"Prevalence rises monotonically as the window widens backwards — the failure rate "
      f"was higher earlier in the panel and declining toward the boundary. The {worst.days}d "
      f"window sits at {worst.prevalence_ratio:.2f}x the test base rate; the {best.days}d "
      f"window at {best.prevalence_ratio:.2f}x.")
    w("")
    w("A 2-parameter Platt map fit at one base rate and applied at another is "
      "miscalibrated by construction, and the intercept absorbs most of that mismatch. "
      "So the §6 selection is a genuine trade-off rather than a formality: the longer "
      "windows buy positives and lose base-rate match, and the Brier-score selection "
      "on the validation window is what should adjudicate it. **This report does not "
      "pick a window — it states what the choice is between.**")
    w("")

    # -- null rates --------------------------------------------------------------------
    w("## 4. Per-column null rates")
    w("")
    n = len(matrix)
    w("| Group | Column | dtype | Nulls | Null rate | Distinct |")
    w("|---|---|---|---:|---:|---:|")
    for group in DEFAULT_GROUPS:
        for col in GROUP_OF[group]:
            if col not in matrix.columns:
                continue
            s = matrix[col]
            n_null = int(s.isna().sum())
            w(f"| {group} | `{col}` | {s.dtype} | {n_null:,} | {pct(n_null, n)} | "
              f"{s.nunique(dropna=True):,} |")
    w("")

    # -- degenerate columns ------------------------------------------------------------
    constant = [c for c in matrix.columns if matrix[c].nunique(dropna=True) <= 1]
    near_empty = [
        c for c in matrix.columns
        if c not in constant and matrix[c].isna().mean() >= 0.95
    ]
    w("### Degenerate columns")
    w("")
    if constant:
        w("**Zero variance — carries no information as built:**")
        w("")
        for c in constant:
            vals = matrix[c].dropna().unique()
            val = vals[0] if len(vals) else "all null"
            w(f"- `{c}` — single value `{val}` across all {n:,} rows.")
        w("")
        w("A constant column cannot produce a split, so it costs nothing at training "
          "time and contributes nothing. It is left in rather than dropped because it "
          "is part of the production availability contract and becomes informative the "
          "moment a source can be absent; on Olist that source never is. Flagged here "
          "so it is a known no-op rather than an assumed signal.")
    else:
        w("No zero-variance columns.")
    w("")
    if near_empty:
        w(f"**At least 95% null** — {', '.join('`' + c + '`' for c in near_empty)}. "
          "See the customer-history note below; these are not defects, they are the "
          "repeat-purchase rate.")
        w("")

    # -- the customer-history problem, named ------------------------------------------
    zero_hist = int((matrix["cust_prior_orders"] == 0).sum())
    w("### What the null rates say")
    w("")
    w(f"**Customer history is almost entirely empty.** {zero_hist:,} of {n:,} orders "
      f"({pct(zero_hist, n)}) have no prior order from the same customer, so every "
      "expanding-window feature is null or zero for them. That is Olist's ~3% "
      "repeat-purchase rate showing up exactly where ARCHITECTURE.md §5.4 predicted it "
      "would, and it is the same fact that made the TabPFN cold-start router "
      "unevaluable. The customer group is built, PIT-correct, and carries almost no "
      "signal on this dataset. It is retained because the production feature contract "
      "includes it and because the smoothed encoding degrades gracefully to the global "
      "prior — not because it is expected to contribute here.")
    w("")
    w("**Pincode history is the group that actually populates.** Every order has a zip "
      "prefix, and the panel is dense enough that the smoothed target encoding has real "
      "observations behind it for most rows. ARCHITECTURE.md §4.5 expects this to "
      "outrank the address-string features, and on Olist it is the only history-derived "
      "signal with enough coverage to matter.")
    w("")
    w(f"Smoothing constants: pincode `m={PINCODE_SMOOTHING:g}`, customer "
      f"`m={CUSTOMER_SMOOTHING:g}` pseudo-observations at the running global rate. "
      "Strong by design — a pincode with a handful of prior orders cannot take an "
      "extreme value, which is what stops the encoding degenerating into a blanket "
      "blacklist (§4.5, §10).")
    w("")

    # -- excluded groups ---------------------------------------------------------------
    w("## 5. Feature groups deliberately absent")
    w("")
    w("Per ARCHITECTURE.md §4.2, the shipped model is trained only on Olist-populated "
      "features. **Address** and **network/ring** are excluded from this matrix:")
    w("")
    w("| Group | Status | Why |")
    w("|---|---|---|")
    w("| Address (~12 regex/vocab features) | **[BUILT-UNEVAL]**, not built yet | Olist "
      "carries no address strings |")
    w("| Network / ring | **[BUILT-UNEVAL]**, not built yet | Olist carries no device "
      "identifiers or phone numbers |")
    w("| Device / session | **[DESIGN]** | Absent from Olist entirely |")
    w("")
    w("`tests/test_feature_builder.py::test_address_and_ring_groups_are_absent` asserts "
      "no column from those groups reaches this matrix.")
    w("")

    report = "\n".join(L) + "\n"
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(report, encoding="utf-8")

    saved = ""
    try:
        MATRIX_PATH.parent.mkdir(parents=True, exist_ok=True)
        out = matrix.copy()
        out[PRIMARY_LABEL] = population[PRIMARY_LABEL].to_numpy()
        out["split"] = population["split"].to_numpy()
        out.to_parquet(MATRIX_PATH, index=False)
        saved = f"\n[written] {MATRIX_PATH.relative_to(REPO_ROOT)}"
    except Exception as exc:  # pyarrow not installed, etc.
        saved = f"\n[matrix not persisted: {type(exc).__name__}: {exc}]"

    print(report)
    print(f"[written] {OUT_PATH.relative_to(REPO_ROOT)}{saved}")
    return 0 if pit_full == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
