#!/usr/bin/env python3
"""
D1: the headline block, generated from eval/TIER1_LOCK.json.

Every number in the block is read from the lock at run time.  Nothing is typed.  That is
the whole point of the task: this repo has now found stale hand-typed figures in two
generated reports, in four documentation files and in a top-level README bullet, and the
headline block is the most-read text in the repository.

The block is injected between markers into README.md and ARCHITECTURE.md §9, identically.
``tests/test_headline_block.py`` asserts both copies match what this script produces from
the current lock, so a lock that moves without the docs following fails the suite.

--------------------------------------------------------------------------------------
WHY THE OPERATING POINT LEADS, AND AVERAGE PRECISION DOES NOT
--------------------------------------------------------------------------------------

Measured, then decided.  Precision at the 1% budget is 3.89x the base rate with a Wilson
interval that excludes the base rate, so the strongest defensible claim is about the top
of the ranking - which is the only part of it the policy layer ever acts on.  Average
precision integrates the entire curve, including the 99% of orders nothing is ever done
about, so it is context rather than the headline.

**The block must not say the model "cannot be shown to beat the base rate".**  That was
``eval/model_report.md`` §1's conclusion, drawn by comparing a point estimate against a
planning heuristic, and ``eval/significance.md`` §5 explicitly corrects it: the paired
bootstrap CI excludes zero and the permutation null gives p = 0.00060.  Repeating the old
framing here would restate a conclusion this repo has already overturned.

Usage
-----
    python scripts/91_headline_block.py [--check]

``--check`` prints the block and exits non-zero if either document is out of date,
without writing anything.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = REPO_ROOT / "eval" / "TIER1_LOCK.json"

BEGIN = "<!-- HEADLINE:BEGIN — generated by scripts/91_headline_block.py, do not edit -->"
END = "<!-- HEADLINE:END -->"

TARGETS = (REPO_ROOT / "README.md", REPO_ROOT / "ARCHITECTURE.md")

SUPPORTED_LOCK_VERSION = 2


class HeadlineError(RuntimeError):
    """The lock is not the shape this generator knows how to render."""


def _wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score interval - the right one at these counts, where normal-approximation
    intervals run below zero and Clopper-Pearson is needlessly wide."""
    if n <= 0:
        raise HeadlineError("cannot form an interval on zero trials")
    p = k / n
    den = 1.0 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return centre - half, centre + half


def load_lock() -> dict:
    if not LOCK_PATH.exists():
        raise HeadlineError(
            f"{LOCK_PATH} is missing; run scripts/90_capture_tier1_lock.py first"
        )
    lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    version = lock.get("lock_version")
    if version != SUPPORTED_LOCK_VERSION:
        raise HeadlineError(
            f"lock_version is {version!r}, this generator renders "
            f"{SUPPORTED_LOCK_VERSION}. A lock of a different shape is refused rather "
            "than rendered against the wrong field names."
        )
    return lock


def build_block(lock: dict) -> str:
    primary = lock["targets"]["primary"]
    ds = primary["dataset"]
    perf = primary["performance"]
    res = primary["resolution"]
    ops = primary["operating_points"]

    n = ds["test_rows"]
    positives = ds["test_positives"]
    base = ds["test_prevalence"]

    def budget(key: str, frac: float) -> dict:
        o = ops[key]
        treated = math.ceil(frac * n)
        tp = round(o["recall"] * positives)
        lo, hi = _wilson(tp, treated)
        return {"treated": treated, "tp": tp, "precision": o["precision"],
                "lift": o["precision"] / base, "ci_low": lo, "ci_high": hi}

    top1 = budget("top_1pct", 0.01)
    top5 = budget("top_5pct", 0.05)

    elk = ops["elkan_policy"]
    elk_treated = round(elk["treated_frac"] * n)
    elk_tp = round(elk["recall"] * positives)
    elk_lo, elk_hi = _wilson(elk_tp, elk_treated)

    ci_lo, ci_hi = res["paired_bootstrap_ci"]

    def pct(x: float, dp: int = 2) -> str:
        return f"{100 * x:.{dp}f}%"

    lines: list[str] = []
    w = lines.append

    w("### Headline numbers")
    w("")
    w(f"**Where the system acts.** The top **{top1['treated']:,}** orders — the top 1% of "
      f"a {n:,}-order test window — contain **{top1['tp']} of {positives}** failures. "
      f"That is **{top1['lift']:.1f}× the base rate** of {pct(base, 3)}: precision "
      f"{pct(top1['precision'])}, Wilson 95% CI "
      f"[{pct(top1['ci_low'])}, {pct(top1['ci_high'])}], which excludes the base rate.")
    w("")
    w(f"At the 5% budget: **{top5['treated']:,}** orders, **{top5['tp']} of {positives}** "
      f"failures, precision {pct(top5['precision'])} — {top5['lift']:.2f}× the base rate.")
    w("")
    w(f"**The set actually acted on is smaller than either.** The per-order Elkan cost "
      f"policy treats **{elk_treated} orders** ({pct(elk['treated_frac'], 3)}) and catches "
      f"**{elk_tp} of {positives}**. Its {pct(elk['precision'])} precision is the largest "
      f"multiple on this page at {elk['precision'] / base:.1f}×, and it rests on "
      f"{elk_tp} positives: the 95% CI is [{pct(elk_lo)}, {pct(elk_hi)}], spanning most "
      "of the plausible range. Stated as a count rather than dressed as a rate.")
    w("")
    w("**The ranking resolves.** Permutation test against random ranking: "
      f"**p = {res['permutation_p']:.5f}**, with the observed average precision above the "
      f"null 99th percentile of {res['permutation_null_p99']:.4f}. Paired bootstrap on the "
      f"AP difference against the prevalence baseline: **{res['paired_bootstrap_delta']:+.4f}"
      f", 95% CI [{ci_lo:+.4f}, {ci_hi:+.4f}]**, excluding zero.")
    w("")
    w(f"**Average precision is {perf['average_precision']:.4f}** against a "
      f"{base:.5f} prevalence baseline, with ROC-AUC {perf['roc_auc']:.4f}. Context rather "
      "than the headline: average precision integrates the whole curve, including the 99% "
      "of orders nothing is ever done about, and this system only acts on the top of it.")
    w("")
    w(f"**Minimum detectable difference {res['mdd_ap']:.3f}** — a *planning* figure, and "
      f"superseded. {res['mdd_superseded_by']}. It is quoted here once, as the planning "
      "figure it was, and never as a decision rule.")
    w("")
    w(f"<sub>Generated from `eval/TIER1_LOCK.json` (lock_version "
      f"{lock['lock_version']}, model `{lock['metadata']['model_version']}`) by "
      "`scripts/91_headline_block.py`. Latency is deliberately absent: it is a wall-clock "
      "measurement whose spread across runs exceeds the quantity being reported — see "
      "`eval/latency.md`.</sub>")

    return "\n".join(lines)


def render(lock: dict) -> str:
    return f"{BEGIN}\n\n{build_block(lock)}\n\n{END}"


def _line_ending(path: Path) -> str:
    """
    The file's dominant line ending.

    Writing with a hardcoded ``\n`` rewrites every line of a CRLF file, which turns a
    three-paragraph edit into a whole-file diff and buries the change under review.  This
    is not hypothetical: an earlier version of this script did exactly that to README.md
    and ARCHITECTURE.md, producing a 767-line diff for a 20-line change.

    Detected rather than assumed, because this repo's markdown is CRLF and there is no
    ``.gitattributes`` normalising it.
    """
    raw = path.read_bytes()
    crlf = raw.count(b"\r\n")
    lf_only = raw.count(b"\n") - crlf
    return "\r\n" if crlf > lf_only else "\n"


def _replace(text: str, block: str, path: Path) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(text):
        raise HeadlineError(
            f"{path.name} has no HEADLINE:BEGIN/END markers. Add them where the block "
            "belongs; this script will not guess a location."
        )
    return pattern.sub(lambda _: block, text, count=1)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the headline block from the lock.")
    ap.add_argument("--check", action="store_true",
                    help="verify both documents are current; write nothing")
    args = ap.parse_args()

    lock = load_lock()
    block = render(lock)

    stale: list[str] = []
    for path in TARGETS:
        text = path.read_text(encoding="utf-8")
        updated = _replace(text, block, path)
        if updated == text:
            continue
        stale.append(path.name)
        if not args.check:
            path.write_text(updated, encoding="utf-8", newline=_line_ending(path))

    if args.check:
        print(block)
        if stale:
            print(f"\nOUT OF DATE: {', '.join(stale)}", file=sys.stderr)
            return 1
        print("\nboth documents match the lock", file=sys.stderr)
        return 0

    print(block)
    print(f"\n[written] {', '.join(p.name for p in TARGETS)}"
          + (f" (updated: {', '.join(stale)})" if stale else " (already current)"))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except HeadlineError as exc:
        print(f"HEADLINE BLOCK FAILED: {exc}", file=sys.stderr)
        raise SystemExit(1)
