"""Responder policy table provenance and generation checks."""

from responder.policy_table import generate


def test_policy_table_is_generated_from_replay():
    text = generate()
    assert "Generated by `responder/policy_table.py`" in text
    assert "RTO cost avoided" in text
    assert "Net" in text
    assert text.count("[MEASURED]") >= 24


def test_policy_table_has_four_rows():
    text = generate()
    assert text.count("| Intervene on nothing |") == 1
    assert text.count("| Intervene on everything |") == 1
    assert text.count("| Hand-written business rule |") == 1
    assert text.count("| Model + cost policy |") == 1